export const UpdatesMutations = {
  UPDATES: 'UPDATES_MUTATION',
  TOGGLE_LOADING: 'TOGGLE_LOADING_MUTATION',
}

export const UpdatesActions = {
  UPDATES: 'UPDATES_ACTION',
}

export const LocationMutations = {
  TOGGLE_LOADING: 'TOGGLE_LOADING_MUTATION',
  ADDRESS: 'ADDRESS_MUTATION',
  SET_LAT_LON: 'SET_LAT_LON_MUTATION',
}

export const LocationActions = {
  ADDRESS: 'ADDRESS_ACTION',
  SET_LAT_LON: 'SET_LAT_LON_ACTION',
}

export const newsMutations = {
  LOADING: 'LOADING_MUTATION',
  TOP_NEWS: 'TOP_NEWS_MUTATION',
}

export const newsActions = {
  TOP_NEWS: 'TOP_NEWS_ACTION',
}

export const StateDistrictsMutations = {
  LOADING: 'LOADING_MUTATION',
  STATES: 'STATES_MUTATION',
  DISTRICTS: 'DISTRICTS_MUTATION',
  PINCODES: 'PINCODES_MUTATION',
}

export const StateDistrictsActions = {
  STATES: 'STATES_ACTION',
  DISTRICTS: 'DISTRICTS_ACTION',
  PINCODES: 'PINCODES_ACTION',
}

export const VaccinationCenterMutations = {
  LOADING: 'LOADING_MUTATION',
  VACCINATION_CENTER: 'VACCINATION_CENTER_MUTATION',
}

export const VaccinationCenterActions = {
  STATES: 'STATES_ACTION',
  VACCINATION_CENTER: 'VACCINATION_CENTER_ACTION',
}

export const LoginMutations = {
  LOADING: 'LOADING_MUTATION',
  LOGIN: 'LOGIN_MUTATION',
  LOGOUT: 'LOGOUT_MUTATION',
  IS_LOGGED_IN: 'IS_LOGGED_IN_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
}

export const LoginActions = {
  LOGIN: 'LOGIN_ACTION',
  LOGOUT: 'LOGOUT_ACTION',
  IS_LOGGED_IN: 'IS_LOGGED_IN_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
}

export const RegisterMutations = {
  LOADING: 'LOADING_MUTATION',
  REGISTER: 'REGISTER_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
}

export const RegisterActions = {
  REGISTER: 'REGISTER_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
}
