export const UpdatesMutations = {
  UPDATES: 'UPDATES_MUTATION',
  LOADING: 'TOGGLE_LOADING_MUTATION',
}

export const UpdatesActions = {
  UPDATES: 'UPDATES_ACTION',
}

export const LocationMutations = {
  LOADING: 'TOGGLE_LOADING_MUTATION',
  ADDRESS: 'ADDRESS_MUTATION',
  SET_LAT_LON: 'SET_LAT_LON_MUTATION',
}

export const LocationActions = {
  ADDRESS: 'ADDRESS_ACTION',
  SET_LAT_LON: 'SET_LAT_LON_ACTION',
}

export const newsMutations = {
  LOADING: 'LOADING_MUTATION',
  TOP_NEWS: 'TOP_NEWS_MUTATION',
}

export const newsActions = {
  TOP_NEWS: 'TOP_NEWS_ACTION',
}

export const StateDistrictsMutations = {
  LOADING: 'LOADING_MUTATION',
  STATES: 'STATES_MUTATION',
  DISTRICTS: 'DISTRICTS_MUTATION',
  PINCODES: 'PINCODES_MUTATION',
}

export const StateDistrictsActions = {
  STATES: 'STATES_ACTION',
  DISTRICTS: 'DISTRICTS_ACTION',
  PINCODES: 'PINCODES_ACTION',
}

export const VaccinationCenterMutations = {
  LOADING: 'LOADING_MUTATION',
  VACCINATION_CENTER: 'VACCINATION_CENTER_MUTATION',
}

export const VaccinationCenterActions = {
  STATES: 'STATES_ACTION',
  VACCINATION_CENTER: 'VACCINATION_CENTER_ACTION',
}

export const LoginMutations = {
  LOADING: 'LOADING_MUTATION',
  LOGIN: 'LOGIN_MUTATION',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN_MUTATION',
  FACEBOOK_LOGIN: 'FACEBOOK_LOGIN_MUTATION',
  LOGOUT: 'LOGOUT_MUTATION',
  IS_LOGGED_IN: 'IS_LOGGED_IN_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
}

export const LoginActions = {
  LOGIN: 'LOGIN_ACTION',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN_ACTION',
  FACEBOOK_LOGIN: 'FACEBOOK_LOGIN_ACTION',
  LOGOUT: 'LOGOUT_ACTION',
  IS_LOGGED_IN: 'IS_LOGGED_IN_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
}

export const RegisterMutations = {
  LOADING: 'LOADING_MUTATION',
  REGISTER: 'REGISTER_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
}

export const RegisterActions = {
  REGISTER: 'REGISTER_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
}

export const ProfileMutations = {
  LOADING: 'LOADING_MUTATION',
  PROFILE: 'PROFILE_MUTATION',
}

export const ProfileActions = {
  PROFILE: 'PROFILE_ACTION',
}

export const BeneficiaryMutations = {
  LOADING: 'LOADING_MUTATION',
  ADD_BENEFICIARY: 'ADD_BENEFICIARY_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
  SET_SUCCESS: 'SET_SUCCESS_MUTATION',
  BENEFICIARIES: 'BENEFICIARIES_MUTATION',
  DELETE_BENEFICIARIES_SCHEDULE: 'DELETE_BENEFICIARIES_SCHEDULE_MUTATION',
  DELETE_BENEFICIARIES: 'DELETE_BENEFICIARIES_MUTATION',
}

export const BeneficiaryActions = {
  ADD_BENEFICIARY: 'ADD_BENEFICIARY_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
  BENEFICIARIES: 'BENEFICIARIES_ACTION',
  DELETE_BENEFICIARIES_SCHEDULE: 'DELETE_BENEFICIARIES_SCHEDULE_ACTION',
  DELETE_BENEFICIARIES: 'DELETE_BENEFICIARIES_ACTION',
}

export const ScheduleMutations = {
  LOADING: 'LOADING_MUTATION',
  SCHEDULE: 'SCHEDULE_MUTATION',
  SCHEDULE_BY_ID: 'SCHEDULE_BY_ID_MUTATION',
  SET_ERROR: 'SET_ERROR_MUTATION',
  SET_SUCCESS: 'SET_SUCCESS_MUTATION',
  UPDATE: 'UPDATE_MUTATION',
}

export const ScheduleActions = {
  SCHEDULE: 'SCHEDULE_ACTION',
  SCHEDULE_BY_ID: 'SCHEDULE_BY_ID_ACTION',
  SET_ERROR: 'SET_ERROR_ACTION',
  SET_SUCCESS: 'SET_SUCCESS_MUTATION',
  UPDATE: 'UPDATE_MUTATION',
}
